# Channel Generator Configuration
extends: "base.yml"

# Channel-specific settings
type: "channel"
category: "real_time"
description: "Generate WebSocket channels for real-time communication"

# Directories specific to channels
directories:
  source: "src/channels"
  spec: "spec/channels"

# Templates for channel generation
templates:
  main: "channel/channel.cr.ecr"
  spec: "channel/channel_spec.cr.ecr"

# Channel types and characteristics
channel_types:
  basic:
    description: "Basic WebSocket channel"
    includes: ["message_handling", "lifecycle_methods"]
    
  authenticated:
    description: "Authenticated WebSocket channel"
    includes: ["message_handling", "lifecycle_methods", "authentication"]
    
  broadcast:
    description: "Broadcasting WebSocket channel"
    includes: ["message_handling", "lifecycle_methods", "broadcasting"]

# Default events for channels
default_events:
  - "message"
  - "connect"
  - "disconnect"

# WebSocket lifecycle methods
lifecycle_methods:
  - "on_connect"
  - "on_disconnect"
  - "on_message"
  - "on_error"

# Authentication patterns
auth_patterns:
  token: "Token-based authentication"
  session: "Session-based authentication"
  jwt: "JWT token authentication"

# Usage examples
usage_examples:
  - "azu generate channel ChatChannel"
  - "azu generate channel NotificationChannel --auth"
  - "azu generate channel GameChannel event:move event:chat"

# Next steps
next_steps:
  - "Implement message handling in src/channels/%{snake_case_name}_channel.cr"
  - "Configure WebSocket routes in your server"
  - "Add authentication if needed"
  - "Test your channel in spec/channels/%{snake_case_name}_channel_spec.cr"