# Handler Generator Configuration
extends: "base.yml"

# Handler-specific settings
type: "handler"
category: "http"
description: "Generate HTTP handlers for request processing"

# Directories specific to handlers
directories:
  source: "src/handlers"
  spec: "spec/handlers"

# Templates for handler generation
templates:
  main: "handler/handler.cr.ecr"
  spec: "handler/handler_spec.cr.ecr"

# Handler types and their characteristics
handler_types:
  auth:
    description: "Authentication handler for verifying credentials"
    includes: ["token_validation", "user_context", "error_handling"]

  cors:
    description: "CORS handler for cross-origin requests"
    includes: ["cors_headers", "preflight_handling"]

  rate_limit:
    description: "Rate limiting handler for request throttling"
    includes: ["rate_tracking", "limit_enforcement"]

  logging:
    description: "Logging handler for request/response tracking"
    includes: ["request_logging", "response_logging", "timing"]

  security:
    description: "Security handler for various security measures"
    includes: ["security_headers", "input_validation"]

  custom:
    description: "Custom handler with basic structure"
    includes: ["basic_handling"]

# Authentication methods
auth_methods:
  bearer: "Bearer token authentication"
  basic: "Basic HTTP authentication"
  jwt: "JWT token validation"
  session: "Session-based authentication"

# Security headers
security_headers:
  - "X-Frame-Options"
  - "X-Content-Type-Options"
  - "X-XSS-Protection"
  - "Content-Security-Policy"
  - "Strict-Transport-Security"

# Usage examples
usage_examples:
  - "azu generate handler AuthHandler type:auth"
  - "azu generate handler CorsHandler type:cors"
  - "azu generate handler RateLimitHandler type:rate_limit"
  - "azu generate handler SecurityHandler type:security"

# Next steps
next_steps:
  - "Implement handler logic in src/handlers/%{snake_case_name}_handler.cr"
  - "Add the handler to your application middleware stack"
  - "Configure handler options as needed"
  - "Test your handler in spec/handlers/%{snake_case_name}_handler_spec.cr"
